export const gettysburgTheme = {
  id: "gettysburg",
  traits: [
    "Builder",
    "Creative",
    "Clutch",
    "Leader",
    "Team Player",
    "Problem Solver",
    "Technical",
    "Organized",
    "Curious",
    "Energetic",
    "Focused",
    "Strategic",
    "Adaptable",
    "Resilient",
    "Collaborative",
    "Inventive",
    "Analytical",
    "Reliable",
    "Bold",
    "Empathetic",
    "Communicator",
    "Detail-Oriented",
    "Initiator",
    "Mentor",
    "Connector",
  ],
  rarities: ["Common", "Rare", "Epic", "Legend", "Campus Myth"],
} as const;
