export const gettysburgTheme = {
  id: "gettysburg",
  name: "Gettysburg College Edition",
  eyebrow: "Campus Pack 001",
  titles: [
    "Campus Catalyst",
    "Gettysburg Spark",
    "First-Year Force",
    "Bullet Builder",
  ],
  stats: [
    "Creativity",
    "Leadership",
    "Focus",
    "Campus Energy",
    "Chaos Control",
    "Execution",
  ],
  traits: [
    "Builder",
    "Creative",
    "Clutch",
    "Leader",
    "Team Player",
    "Problem Solver",
    "Technical",
    "Organized",
    "Curious",
    "Energetic",
    "Focused",
    "Strategic",
    "Adaptable",
    "Resilient",
    "Collaborative",
    "Inventive",
    "Analytical",
    "Reliable",
    "Bold",
    "Empathetic",
    "Communicator",
    "Detail-Oriented",
    "Initiator",
    "Mentor",
    "Connector",
  ],
  rarities: ["Common", "Rare", "Epic", "Legend", "Campus Myth"],
} as const;

export const themePacks = [gettysburgTheme] as const;
